title: FJP — FireJail-Profile
description: >-
  A handy command line program to work fast and straightforward with firejail profiles.

theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
fjp_version: 0.2.0
fjp_rc_version: 0.3.0-rc4
