[package]
name = "macros"
version = "0.2.0-rc1"
description = "Procedural Macros for fjp"
authors = ["rusty-snake"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
