name: ShellCheck

on:
  push:
    paths:
      - .github/workflows/shellcheck.yml
      - 'make.sh'
      - 'platform/fedora/mkrpm.sh'
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - 'make.sh'
      - 'platform/fedora/mkrpm.sh'

jobs:
  shellcheck:
    name: shellcheck
    if: ${{ ! contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: shellcheck --version
    - run: shellcheck make.sh
    - run: shellcheck platform/fedora/mkrpm.sh
